job is rerunnable

diff --git a/charts/pulsar/templates/pulsar-manager-cluster-initialize.yaml b/charts/pulsar/templates/pulsar-manager-cluster-initialize.yaml
--- a/charts/pulsar/templates/pulsar-manager-cluster-initialize.yaml
+++ b/charts/pulsar/templates/pulsar-manager-cluster-initialize.yaml
@@ -91,24 +91,40 @@ spec:
             - |
               ADMIN_URL={{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}-admin:{{ .Values.pulsar_manager.adminService.port }}
               CSRF_TOKEN=$(curl http://${ADMIN_URL}/pulsar-manager/csrf-token)
-              {{/* set admin credentials */}}
-              curl -v \
-                -X PUT http://${ADMIN_URL}/pulsar-manager/users/superuser \
-                -H "X-XSRF-TOKEN: $CSRF_TOKEN" \
-                -H "Cookie: XSRF-TOKEN=$CSRF_TOKEN;" \
-                -H 'Content-Type: application/json' \
-                -d '{"name": "'"${USERNAME}"'", "password": "'"${PASSWORD}"'", "description": "Helm-managed Admin Account", "email": "'"${USERNAME}"'@pulsar.org"}'
-
               UI_URL={{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}:{{ .Values.pulsar_manager.service.port }}
-              {{/* login as admin */}}
-              curl -v \
+
+              {{/* check if account is already existing */}}
+              LOGIN_REPLY=$(curl -v \
                 -X POST http://${UI_URL}/pulsar-manager/login \
                 -H 'Accept: application/json, text/plain, */*' \
                 -H 'Content-Type: application/json' \
                 -H "X-XSRF-TOKEN: $CSRF_TOKEN" \
                 -H "Cookie: XSRF-TOKEN=$CSRF_TOKEN" \
                 -sS -D headers.txt \
-                -d '{"username": "'${USERNAME}'", "password": "'${PASSWORD}'"}'
+                -d '{"username": "'${USERNAME}'", "password": "'${PASSWORD}'"}')
+              echo "$LOGIN_REPLY"
+
+              if [ -n "$(echo "$LOGIN_REPLY" | grep 'success')" ]; then
+                echo "account already exists"
+              else
+                echo "creating account"
+                {{/* set admin credentials */}}
+                curl -v \
+                  -X PUT http://${ADMIN_URL}/pulsar-manager/users/superuser \
+                  -H "X-XSRF-TOKEN: $CSRF_TOKEN" \
+                  -H "Cookie: XSRF-TOKEN=$CSRF_TOKEN;" \
+                  -H 'Content-Type: application/json' \
+                  -d '{"name": "'"${USERNAME}"'", "password": "'"${PASSWORD}"'", "description": "Helm-managed Admin Account", "email": "'"${USERNAME}"'@pulsar.org"}'
+                {{/* login as admin */}}
+                curl -v \
+                  -X POST http://${UI_URL}/pulsar-manager/login \
+                  -H 'Accept: application/json, text/plain, */*' \
+                  -H 'Content-Type: application/json' \
+                  -H "X-XSRF-TOKEN: $CSRF_TOKEN" \
+                  -H "Cookie: XSRF-TOKEN=$CSRF_TOKEN" \
+                  -sS -D headers.txt \
+                  -d '{"username": "'${USERNAME}'", "password": "'${PASSWORD}'"}'
+              fi
 
               LOGIN_TOKEN=$(grep "token:" headers.txt | sed 's/^.*: //')
               LOGIN_JSESSSIONID=$(grep -o "JSESSIONID=[a-zA-Z0-9_]*" headers.txt | sed 's/^.*=//')
@@ -122,20 +138,23 @@ spec:
               BOOKIE_URL="http://{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}:{{ .Values.bookkeeper.ports.http }}"
               echo '{ "name": "{{ template "pulsar.fullname" . }}", "broker": "'$BROKER_URL'", "bookie": "'$BOOKIE_URL'"}'
 
-              nslookup {{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}
-              nslookup {{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}
-
-              curl $BROKER_URL
-              curl $BOOKIE_URL
-
-              curl -v \
+              ENVIRONMENT_REPLY=$(curl -v \
                 -X PUT http://${UI_URL}/pulsar-manager/environments/environment \
                 -H 'Content-Type: application/json' \
                 -H "token: $LOGIN_TOKEN" \
                 -H "X-XSRF-TOKEN: $CSRF_TOKEN" \
                 -H "username: $USERNAME" \
                 -H "Cookie: XSRF-TOKEN=$CSRF_TOKEN; JSESSIONID=$LOGIN_JSESSSIONID;" \
-                -d '{ "name": "{{ template "pulsar.fullname" . }}", "broker": "'$BROKER_URL'", "bookie": "'$BOOKIE_URL'"}'
+                -d '{ "name": "{{ template "pulsar.fullname" . }}", "broker": "'$BROKER_URL'", "bookie": "'$BOOKIE_URL'"}')
+              echo "$ENVIRONMENT_REPLY"
+
+              if [ -n "$(echo "$ENVIRONMENT_REPLY" | grep 'success')" ]; then
+                echo "Successfully created environment"
+                exit 0
+              else
+                echo "Error creating environment"
+                exit 1
+              fi
           env:
             - name: USERNAME
               valueFrom:
